### ISSUE TITLE
[PE] JRakLib Server crash on 0.12 spawn

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#108]
I successfully spawn using 0.12 build 12, and then finally the server crashes. Log:
```
ready!
[18:19:50] [DEBUG] [JRakLibInterface]: (169.254.137.101:19132) PACKET OUT: 0xbc,00,00,00,a0,
[18:19:50] [DEBUG] [JRakLibInterface]: (169.254.137.101:19132) PACKET OUT: 0xad,00,00,00,00,00,00,00,00,00,00,10,00,21,2c,01,82,05,00,53,74,65,76,65,03,01,04,00,47,00,00,00,00,08,00,0f,00,7f,
[18:19:50] [DEBUG] [JRakLibInterface]: (169.254.137.101:19132) PACKET OUT: 0x94,00,00,00,01,01,
[18:19:50] [DEBUG] [JRakLibInterface]: (169.254.137.101:19132) PACKET OUT: 0xb3,43,00,00,00,40,40,00,00,43,00,00,00,
[18:19:50] [DEBUG] [JRakLibInterface]: (169.254.137.101:19132) PACKET OUT: 0x90,00,00,00,03,
[18:19:50] [DEBUG] [RedstoneLamp]: Player Steve spawned (took 1264 ms)
Exception in thread "JRakLib Thread #13" java.lang.RuntimeException: java.nio.BufferUnderflowException
	at net.beaconpe.jraklib.server.SessionManager.run(SessionManager.java:95)
	at net.beaconpe.jraklib.server.SessionManager.<init>(SessionManager.java:80)
	at net.beaconpe.jraklib.server.JRakLibServer.run(JRakLibServer.java:120)
Caused by: java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at net.beaconpe.jraklib.Binary.subbytes(Binary.java:219)
	at net.beaconpe.jraklib.protocol.EncapsulatedPacket.fromBinary(EncapsulatedPacket.java:95)
	at net.beaconpe.jraklib.protocol.DataPacket._decode(DataPacket.java:68)
	at net.beaconpe.jraklib.protocol.Packet.decode(Packet.java:206)
	at net.beaconpe.jraklib.server.Session.handlePacket(Session.java:451)
	at net.beaconpe.jraklib.server.SessionManager.receivePacket(SessionManager.java:173)
	at net.beaconpe.jraklib.server.SessionManager.tickProcessor(SessionManager.java:105)
	at net.beaconpe.jraklib.server.SessionManager.run(SessionManager.java:93)
	... 2 more
[18:19:50] [ERROR] [RedstoneLamp]: [JRakLibInterface]: JRakLib Server crashed!
```

**Comment by RandomAltThingy** [comment]
I haven't seen this happening

**Comment by jython234** [comment]
That's because we use JRakLibPlus, which doesn't crash.

On Sunday, September 20, 2015, RandomAltThingy <notifications@github.com>
wrote:

> I haven't seen this happening
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/108#issuecomment-141820067>
> .
>


--

**Comment by RandomAltThingy** [comment]
Well close this?!?

**Comment by jython234** [comment]
No because this is caused by the bufferunderflow, which is the same problem.

On Sunday, September 20, 2015, RandomAltThingy <notifications@github.com>
wrote:

> Well close this?!?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/108#issuecomment-141820290>
> .
>


--
