### ISSUE TITLE
[JRakLibPlus/JRakLib] BufferUnderflowException while processing CustomPacket (Datagram)

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#119]
Dump (partial)
```
ready!
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xbc,00,00,00,a0,
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xad,00,00,00,00,00,00,00,00,00,00,10,00,21,2c,01,82,09,00,6a,79,74,68,6f,6e,32,33,34,03,01,04,00,47,00,00,00,00,08,00,0f,00,7f,
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x94,00,00,0a,59,01,
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xb3,00,00,00,00,43,00,00,00,40,80,00,00,
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x90,00,00,00,03,
[17:00:33] [DEBUG] [RedstoneLamp]: Player jython234 spawned (took 1659 ms)
[17:00:33] [INFO] [RedstoneLamp]: [Chat]: multiplayer.player.joined [jython234]
[17:00:33] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x93,02,00,1a,25,6d,75,6c,74,69,70,6c,61,79,65,72,2e,70,6c,61,79,65,72,2e,6a,6f,69,6e,65,64,01,00,09,6a,79,74,68,6f,6e,32,33,34,
Sep 20, 2015 5:00:34 PM io.github.jython234.jraklibplus.server.PacketWorker run
WARNING: (/192.168.1.8:19132) Decode Failed! java.nio.BufferUnderflowException: null
Sep 20, 2015 5:00:34 PM io.github.jython234.jraklibplus.server.PacketWorker run
WARNING: BufferUnderFlow: 84 06 00 00 60 01 11 03 00 00 02 00 00 00 9D 00 00 00 00 00 00 00 00 00 00 00 00 43 00 00 00 40 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 60 00 88 04 00 00 03 00 00 00 A8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Sep 20, 2015 5:00:36 PM io.github.jython234.jraklibplus.server.PacketWorker run
WARNING: (/192.168.1.8:19132) Decode Failed! java.nio.BufferUnderflowException: null
Sep 20, 2015 5:00:36 PM io.github.jython234.jraklibplus.server.PacketWorker run
WARNING: BufferUnderFlow: 88 0F 00 00 60 01 11 06 00 00 05 00 00 00 9D 00 00 00 00 00 00 00 00 00 00 00 00 42 FE 76 8A 40 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 01 11 07 00 00 06 00 00 00 9D 00 00 00 00 00 00 00 00 00 00 00 00 42 FC D0 96 40 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
Sep 20, 2015 5:00:36 PM io.github.jython234.jraklibplus.server.PacketWorker run
```

Dump of JRakLib:
```
ready!
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xbc,00,00,00,a0,
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xad,00,00,00,00,00,00,00,00,00,00,10,00,21,2c,01,82,09,00,6a,79,74,68,6f,6e,32,33,34,03,01,04,00,47,00,00,00,00,08,00,0f,00,7f,
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x94,00,00,03,11,01,
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0xb3,00,00,00,00,43,00,00,00,40,80,00,00,
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x90,00,00,00,03,
[21:04:59] [DEBUG] [RedstoneLamp]: Player jython234 spawned (took 1704 ms)
[21:04:59] [INFO] [RedstoneLamp]: [Chat]: multiplayer.player.joined [jython234]
[21:04:59] [DEBUG] [JRakLibInterface]: (192.168.1.8:19132) PACKET OUT: 0x93,02,00,1a,25,6d,75,6c,74,69,70,6c,61,79,65,72,2e,70,6c,61,79,65,72,2e,6a,6f,69,6e,65,64,01,00,09,6a,79,74,68,6f,6e,32,33,34,
Exception in thread "JRakLib Thread #13" java.lang.RuntimeException: java.nio.BufferUnderflowException
	at net.beaconpe.jraklib.server.SessionManager.run(SessionManager.java:95)
	at net.beaconpe.jraklib.server.SessionManager.<init>(SessionManager.java:80)
	at net.beaconpe.jraklib.server.JRakLibServer.run(JRakLibServer.java:120)
Caused by: java.nio.BufferUnderflowException
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
	at net.beaconpe.jraklib.Binary.subbytes(Binary.java:219)
	at net.beaconpe.jraklib.protocol.EncapsulatedPacket.fromBinary(EncapsulatedPacket.java:95)
	at net.beaconpe.jraklib.protocol.DataPacket._decode(DataPacket.java:68)
	at net.beaconpe.jraklib.protocol.Packet.decode(Packet.java:206)
	at net.beaconpe.jraklib.server.Session.handlePacket(Session.java:451)
	at net.beaconpe.jraklib.server.SessionManager.receivePacket(SessionManager.java:173)
	at net.beaconpe.jraklib.server.SessionManager.tickProcessor(SessionManager.java:105)
	at net.beaconpe.jraklib.server.SessionManager.run(SessionManager.java:93)
	... 2 more
[21:04:59] [FATAL] [JRakLibInterface]: JRakLib Server crashed!
```

JRakLibPlus prints out a hexdump of the FULL datagram buffer it was trying to process when the exception occurred. The worker thread and server threads do NOT crash, as the exception is caught. Some packets sent from the client, such as Chat Packets, are located inside these packets, and when the exception occurs, the packets inside are dropped as they are failed to be decoded.

**Comment by jython234** [comment]
@RedstoneLamp/developers I reverted to using old JRakLib to fix NACK spam. The decode errors now crash the server though, so a fix must be found quickly.

**Comment by iNevet** [comment]
What caused the exception?

**Comment by jython234** [comment]
A BufferUnderflow exception when attempting to decide a custom packet. This
happens every time and ONLY after the player spawns.

On Friday, September 25, 2015, iNevet <notifications@github.com> wrote:

> What caused the exception?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedstoneLamp/RedstoneLamp/issues/119#issuecomment-143181767>
> .
>


--

**Comment by jython234** [comment]
After some testing, it seems that the client is sending malformed packets to the server. Using wireshark, these packets are only sent to RedstoneLamp, and when testing with a PM server, they do not show up. It also seems these packets are sent only after spawning WITH chunks. If no chunks are sent but the player spawns, then these packets are never received.

**Comment by jython234** [comment]
Fixed as of https://github.com/BlockServerProject/JRakLib/commit/30ebe4b8284da2d4a22a825c168124020e02f3c1
