### ISSUE TITLE
ClassCastException when placing block

### ISSUE THREAD

**Issue by jython234** [RedstoneLamp/RedstoneLamp#135]
```
Exception in thread "NetworkProcessor-6" java.lang.ClassCastException: net.redstonelamp.item.Item cannot be cast to net.redstonelamp.block.Block
        at net.redstonelamp.level.Level.getBlock(Level.java:218)
        at net.redstonelamp.network.pe.sub.v34.SubprotocolV34.handlePacket(SubprotocolV34.java:151)
        at net.redstonelamp.network.pe.PEProtocol.handlePacket(PEProtocol.java:99)
        at net.redstonelamp.network.Protocol.lambda$tick$19(Protocol.java:56)
        at net.redstonelamp.network.Protocol$$Lambda$11/18984340.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by jython234** [comment]
Fixed.
