### ISSUE TITLE
LevelDBProvider not functioning

### ISSUE THREAD

**Issue by SuperstarGamer** [RedstoneLamp/RedstoneLamp#146]
The LevelDBProvider fails to load correctly if the directory is "db" but if it's something else it works fine, but we can't use anything but "db" beacuse MCPE uses "db" so we're kind of stuck.

**Comment by M10360** [comment]
How does it fail to load correctly with "db"?

**Comment by jython234** [comment]
Seems to only happen on Windows 10:
```
[14:28:39] [ERROR] [RedstoneLamp]: java.io.FileNotFoundException while loading LevelDB world worlds\world1\db
 (The filename, directory name, or volume label syntax is incorrect)
 (The filename, directory name, or volume label syntax is incorrect)
	at net.redstonelamp.level.Level.<init>(Level.java:86)
	at net.redstonelamp.level.LevelManager.init(LevelManager.java:75)
	at net.redstonelamp.Server.<init>(Server.java:126)
	at net.redstonelamp.RedstoneLamp.main(RedstoneLamp.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
 (The filename, directory name, or volume label syntax is incorrect)
	at net.redstonelamp.level.provider.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.redstonelamp.level.Level.<init>(Level.java:82)
	... 8 more
 (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:341)
	at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:186)
	at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:59)
	at net.redstonelamp.level.provider.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:75)
	... 13 more
```

**Comment by SuperstarGamer** [comment]
@jython234
Interesting, maybe the C++ and C native part of java for Windows 10 is malfunctioning while it's different but working code on other systems?

**Comment by PEMapModder** [comment]
This is what I get on Windows 8:

```shell
> mvn package
# output omitted

> cd target
> java -jar RedstoneLamp-1.2.0-DEV.jar
[17:14:55] [INFO] [RedstoneLamp]: RedstoneLamp 1.2.0-DEV is licensed under the Lesser GNU General Public License version 3
[17:14:55] [INFO] [RedstoneLamp]: Build Information: RedstoneLamp build #-1, commit: not available, built on: not available
[17:14:55] [INFO] [JRakLibInterface]: MCPE server started on 0.0.0.0:19132
[17:14:55] [INFO] [RedstoneLamp]: Registered protocol: MCPE
Nov 22, 2015 5:14:56 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x93fcb0de] REGISTERED
Nov 22, 2015 5:14:56 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x93fcb0de] BIND: 0.0.0.0/0.0.0.0:25565
[17:14:56] [INFO] [NettyInterface]: Bound to: 0.0.0.0:25565
Nov 22, 2015 5:14:56 PM io.netty.util.internal.logging.Slf4JLogger info
INFO: [id: 0x93fcb0de, /0:0:0:0:0:0:0:0:25565] ACTIVE
[17:14:56] [INFO] [RedstoneLamp]: Registered protocol: MCPC
[17:14:56] [INFO] [PluginSystem]: Loaded PluginSystem and registered default PluginManagers!
[17:14:56] [INFO] [RedstoneLamp]: Default worlds have no generator yet, using packaged world.
[17:14:57] [ERROR] [RedstoneLamp]: java.io.FileNotFoundException while loading LevelDB world worlds\world\db
[17:14:57] [FATAL] []: Could not init server! net.redstonelamp.level.provider.LevelLoadException: net.redstonelamp.level.provider.LevelLoadException: java.io.FileNotFoundException: worlds\world\db\MANIFEST-0
 (The filename, directory name, or volume label syntax is incorrect)
 (The filename, directory name, or volume label syntax is incorrect).level.provider.LevelLoadException: java.io.FileNotFoundException: worlds\world\db\MANIFEST-000002
        at net.redstonelamp.level.Level.<init>(Level.java:86)
        at net.redstonelamp.level.LevelManager.init(LevelManager.java:75)
        at net.redstonelamp.Server.<init>(Server.java:126)
        at net.redstonelamp.RedstoneLamp.main(RedstoneLamp.java:53)
 (The filename, directory name, or volume label syntax is incorrect)io.FileNotFoundException: worlds\world\db\MANIFEST-000002
        at net.redstonelamp.level.provider.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:78)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.redstonelamp.level.Level.<init>(Level.java:82)
        ... 3 more
 (The filename, directory name, or volume label syntax is incorrect)00002
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.iq80.leveldb.impl.VersionSet.recover(VersionSet.java:341)
        at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:186)
        at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:59)
        at net.redstonelamp.level.provider.leveldb.LevelDBProvider.<init>(LevelDBProvider.java:75)
        ... 8 more

**Comment by jython234** [comment]
I get the same on Windows 10. I believe it is a windows issue.

**Comment by PEMapModder** [comment]
I tried to reproduce this on an Ubuntu VPS, then I ended up spending the whole day to fix the compiler requiring jdk 1.8 issue :P
